using Xunit;

namespace ProductManagementApplication.EntityFrameworkCore;

[CollectionDefinition(ProductManagementApplicationTestConsts.CollectionDefinitionName)]
public class ProductManagementApplicationEntityFrameworkCoreCollection : ICollectionFixture<ProductManagementApplicationEntityFrameworkCoreFixture>
{

}
