using Volo.Abp;

namespace ProductManagementApplication.EntityFrameworkCore;

public abstract class ProductManagementApplicationEntityFrameworkCoreTestBase : ProductManagementApplicationTestBase<ProductManagementApplicationEntityFrameworkCoreTestModule>
{

}
