using ProductManagementApplication.EntityFrameworkCore;
using Xunit;

namespace ProductManagementApplication.EntityFrameworkCore;

public class ProductManagementApplicationEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<ProductManagementApplicationEntityFrameworkCoreFixture>
{

}
